EVALFILE 'examples/prepare_lvm.pl6';
EVALFILE 'examples/install_on_lvm.pl6';
EVALFILE 'examples/mount_table.pl6';
EVALFILE 'examples/install_grub.pl6';
EVALFILE 'examples/set_hostname.pl6';
EVALFILE 'examples/root_pass.pl6';
EVALFILE 'examples/set_time.pl6';
EVALFILE 'examples/install_packages.pl6';
EVALFILE 'examples/enable_services.pl6';
